
name: Build
on:
  release:
    types: [released, prereleased]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
      - name: Push Release to Docker Hub
        uses: docker/build-push-action@v2
        if: ${{ !github.event.release.prerelease }}
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/emwiki:${{ steps.tagName.outputs.tag }}
            ${{ secrets.DOCKER_USERNAME }}/emwiki:release
      - name: Push Beta to Docker Hub
        uses: docker/build-push-action@v2
        if: ${{ github.event.release.prerelease }}
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/emwiki:${{ steps.tagName.outputs.tag }}
            ${{ secrets.DOCKER_USERNAME }}/emwiki:beta
